baseurl         = "https://a-view.org/"
title           = "Trips & Places"
theme           = "hugo-casper3"
languageCode    = "en-US"
disqusShortname = "a-view"
paginate        = 12
SectionPagesMenu = "main"
mainSections = ["post"]
canonifyurls    = false
relativeURLs    = true

[params]
  description    = "Stories and Observations"
  cover_image = "/images/2018/06/2013-12-27-16.41.42.jpg"
  copyright   = "© 2019"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Seattle, WA"
  authorWebsite = "https://lewislevin.com"
  pageNotFoundTitle = "404 - Page not found"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "author"

[permalinks]
  post = "/post/:slug/"

# [[menu.main]]
#   name = "Authors"
#   url = "/author/"
#   # weight = -600

[[menu.main]]
   name = "|||"
   url = "/more-trips"
   weight = -100

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false


